# For the next release 
Add your new features and bug fixes to the top of the following list:

* CalcModPerf: option to output pair data frame to an R binary file in a directory.

* GatherStreamInds: removed recusion, some improvements.

* GatherNeighborStreamGages: Find the first upstream gages (dont go beyond any gage).

* MkNudgingParams: Accept/write persistence parameters.

* New MkNudgingParams function and new perfect model nudging vignette. Updates to WriteNcTimeSlice, ReadFrxstPts.

* VisualizeDomain: Improvements to correct projection.

* VisualizeRouteLink: Visualize a Route_Link.nc file.

* Adding the "gage" variable to Route_Link.nc files (reach-based routing) or editing the frxst_pts layer in Fulldom domain files: AddRouteLinkGage, EditFrxstPts. 

* ChanObsToTimeSlice: convert *CHANOBS_DOMAIN* files to timeSlice files for perfect model obsercation experiments with WRF Hydro nudging.

* Route_Link.nc network re-expression for indexed traversal of the stream network:
    * ReIndexRouteLink.Rd: Reindex routelink. 
    * ReExpNetwork.Rd: 
    * ReExpressRouteLink.Rd: Wrapper on previous two.
    * NtwKReExToNcdf.Rd: Output reexpressions to a netcdf file. <br><br>
    
*	GatherStreamInds: traverse up/down stream from a point.

* VisualizeSubsetStream: Visualize the up/downstream network from a point. 

* Functions to import data from the GHCN network of stations, including:
    * SelectGhcnGauges: Reads the daily GHNC metadata and select gauges based on the user criteria.
    * GetGhcn and GetGhcn2: Get GHCN data for specified siteIds.
    * GetTimeZone: Return the time zone for gauge locations (includes a timeZone polygon shapefile of world time zone classifications).
    * CalcDailyGhcn: Aggregate the hourly data into daily data comparable to GHCN daily data.
    * CalcMetCont: Calculate the MET verification measures for continuous variables.  <br><br>
          
* NewFunctions to download and process Ameriflux, SNOTEL, and Colorado DWR data from online data feeds.

* Geospatial tools to export LDASOUT files to geotiffs, obtain geogrid i,j indices from lat/lon coords, and get geospatial info for geogrids.

* Function to read all LDASOUT variables (instead of just water budget vars): ReadLdasoutAll.

* Function to create coarse-resolution (i.e., geogrid) version of high-resolution basin masks: CreateBasinMask.

* Update to getMultiNetcdf to allow indexes as lists to permit passing variable function arguments to stats.


# rwrfhydro 1.0.0
2015-05-01. WRF-Hydro v3.0.0.

## New Features (all are new!)
This is not an exhaustive list, but is simply culled from the more relevant commit messages. Future change logs will be more informative with bug references.

* ReadCoDwrGage: read CO Dept Water Resources Gage files.

* Multi-basin streamflow eval vignette. 

* New reasmple type option to GetMODIS.

* Using Travis-CI via the new .travis.yml file with native R support: automated build checks on push and pull request (incl. slack notification). Ncdf and rgdal are installed during the check. 

* Appending to unlimited dimensions in ncdf files in MkNcdf.

* CalcModPerf accounts for uneven timesteps in timing stats with output as single row for multi-runs.

* Fixed startup to check for updates can be suppressed with suppressPackageStartupMessages().

* GagesII attribute information in gages2Attr and gages2AttrPlus with documentation and attribution. 

* An rwrfhydro discovery vignette.

* Parallelization of GetSnodasDepthSweDate.

* Snodas vignette.

* FormalsToDf: the suggested way to handle vector arguments (collated across multiple vector arguments) to rwrfhydro routines. 

* MODIS processing routines and vignette.

* Common functions in utilities doc.

* PlotFluxCompare and visualize_modeleval.

* Read in LDASOUT and RTOUT files for water budget calcs: CalcNoahmpWatBudg.

* Functionality for reading WRF-Hydro output.

* Reading USGS and Ameriflux obs data.

* Calculating model performance statistics.

* Snodas retrieval and processing to ncdf (incl a useful matrix rotation utility!).

* MkNcdf: list-based creation of ncdf files using netcdf v4 (later added appending to unlimited dimensions).

* VisualizeChanNtwk: Understanding the seemingly random channel network, gauge-link matching, plot options, point selection with maps, etc. 