#' Calculate flow duration curve statistics
#'
#' \code{CalcFdc} calculates flow exceedance probabilities and adds them as a new column to the dataframe.
#'
#' \code{CalcFdc} reads a streamflow time series dataframe (modeled or observed) and outputs a modified dataframe with
#' calculated percent exceedances.
#' 
#' @param strflowDf The streamflow time series dataframe (e.g., output from \code{\link{ReadFrxstPts}} or \code{\link{ReadUsgsGage}}).
#' The data frame must contain a column of streamflow values.
#' @param strflowCol The name of the column containing the streamflow values (DEFAULT="q_cms").
#' @return A dataframe containing the original input data with a new column added called "<strflowCol>.fdc"
#' containing the flow exceedance probabilities.
#'
#' @examples
#' ## Take the time series of observed 5-minute streamflow values for Fourmile Creek (stored in the dataframe
#' ## obsStr5min.fc in the column "q_cms") and return the same dataframe with a new column called "q_cms.fdc"
#' ## containing the flow exceedance probabilities.
#'
#' obsStr5min.fc <- CalcFdc(obsStr5min.fc, "q_cms")
#' @export
CalcFdc <- function(strflowDf, strflowCol="q_cms") {
    tmp <- rank(-strflowDf[,strflowCol],na.last="keep")
    strflowDf[,paste0(strflowCol,".fdc")] <- NA
    strflowDf[,paste0(strflowCol,".fdc")] <- tmp/(sum(!is.na(strflowDf[,strflowCol]))+1)
    strflowDf
}


#' Generate a spline-fit funtion for a flow duration curve
#'
#' \code{CalcFdcSpline} generates a spline fit function for a flow duration curve.
#'
#' \code{CalcFdcSpline} reads the percent exceedances generated by \code{\link{CalcFdc}} and outputs a fitted spline function
#' useful for plotting or estimating flow at specified exceedance thresholds (e.g., 20\% exceedance probability).
#' 
#' @param strflowDf The streamflow time series dataframe (e.g., output from \code{\link{ReadFrxstPts}} or \code{\link{ReadUsgsGage}})
#' already processed through \code{\link{CalcFdc}}. The data frame must contain a column of streamflow values and a
#' corresponding column (named "<strflowCol>.fdc") of flow exceedance probabilities.
#' @param strflowCol The name of the column containing the streamflow values (DEFAULT="q_cms").
#' @return A spline function fitted to flow (y) vs. flow exceedance probabilities (x).
#'
#' @examples
#' ## Take a time series of observed 5-minute streamflow values for Fourmile Creek (stored in the dataframe
#' ## obsStr5min.fc in the column "q_cms") that has already been processed through "CalcFdc" (so also contains
#' ## a column named "q_cms.fdc") and return a spline fit function.
#'
#' fdc.obsStr5min.fc <- CalcFdcSpline(obsStr5min.fc, "q_cms")
#'
#' ## Use the spline function to estimate the flow value that is exceeded 20% of the time.
#'
#' fdc.obsStr5min.fc(0.2)
#' > 0.72
#' @export
CalcFdcSpline <- function(strflowDf, strflowCol="q_cms") {
    strflowSpline <- splinefun(strflowDf[,paste0(strflowCol,".fdc")], strflowDf[,strflowCol], method='natural')
    strflowSpline
}


#' Plot a flow duration curve for a single streamflow time series
#'
#' \code{PlotFdc} plots a flow duration curve from a dataframe processed through \code{\link{CalcFdc}}
#' and optional spline function processed through \code{\link{CalcFdcSpline}}.
#'
#' \code{PlotFdc} reads the dataframe generated by \code{\link{CalcFdc}} and outputs a plot of flow vs.
#' percent exceedances and, optionally the fitted spline curve.
#' 
#' @param strflowDf The streamflow time series dataframe (e.g., output from \code{\link{ReadFrxstPts}} or \code{\link{ReadUsgsGage}})
#' already processed through \code{\link{CalcFdc}}. The data frame must contain a column of streamflow values and a
#' corresponding column (named "<strflowCol>.fdc") of flow exceedance probabilities.
#' @param strflowCol The name of the column containing the streamflow values (DEFAULT="q_cms").
#' @param spline (TRUE or FALSE) Option to add spline-fit curves to the plot (DEFAULT=TRUE).
#' @param fdcProb Optional exceedance threshold to calculate/plot (e.g., 0.2 for 20\% exceedance).
#' @return A plot of flow (y) vs. flow exceedance probabilities (x).
#'
#' @examples
#' ## Take a time series of observed 5-minute streamflow values for Fourmile Creek (stored in the dataframe
#' ## obsStr5min.fc in the column "q_cms") that has already been processed through "CalcFdc" (so also contains
#' ## a column named "q_cms.fdc") and plot with the 20% exceedance threshold called out.
#'
#' PlotFdc(obsStr5min.fc, fdcProb=0.2)
#' @export
PlotFdc <- function(strflowDf, strflowCol="q_cms", spline=TRUE, fdcProb=NULL) {
plot(strflowDf[,paste0(strflowCol,".fdc")], strflowDf[,strflowCol], log='y', xlab="Probability of Exceedance", ylab=c("Flow (log scale)"), main=c(paste("Flow Duration Curve: ", deparse(substitute(strflowDf)), ":", deparse(substitute(strflowCol)), ", n=", sum(!is.na(strflowDf[,strflowCol])))))
if (spline | !is.null(fdcProb)) {
    fdcSplineFun <- splinefun(strflowDf[,paste0(strflowCol,".fdc")], strflowDf[,strflowCol], method='natural')
    if (spline) {
        curve(fdcSplineFun(x), col='red', lwd=2, lty=1, add=T)
        }
    if (!is.null(fdcProb)) {
        abline(v=fdcProb,h=fdcSplineFun(fdcProb),col='grey')
        text(fdcProb,fdcSplineFun(fdcProb),labels=paste("P =",fdcProb*100,"%, Q=",round(fdcSplineFun(fdcProb),2)), adj=c(-0.05,-1), cex=0.9)
        }
    }
}


#' Plots a flow duration curve for up to three streamflow time series (e.g., observed & two model outputs)
#'
#' \code{PlotFdcCompare} plots up to three flow duration curves from dataframes processed through \code{\link{CalcFdc}}.
#'
#' \code{PlotFdcCompare} reads up to three dataframes generated by \code{\link{CalcFdc}} and outputs a plot of
#' flow vs. percent exceedances and, optionally, the fitted spline curves. Intended to plot one observed flow duration
#' curve and one or two modelled flow duration curves for comparison.
#' 
#' @param strflowDf.obs The OBSERVED streamflow time series dataframe (e.g., output from \code{\link{ReadUsgsGage}})
#' already processed through \code{\link{CalcFdc}}. The dataframe must contain a column of streamflow values and a
#' corresponding column (named "<strflowCol>.fdc") of flow exceedance probabilities.
#' @param strflowCol.obs The name of the column containing the streamflow values for the OBSERVED
#' dataframe (DEFAULT="q_cms").
#' @param strflowDf.mod1 The FIRST MODEL streamflow time series dataframe (e.g., output from \code{\link{ReadFrxstPts}})
#' already processed through \code{\link{CalcFdc}}. The dataframe must contain a column of streamflow values and a
#' corresponding column (named "<strflowCol>.fdc") of flow exceedance probabilities.
#' @param strflowCol.mod1 The name of the column containing the FIRST MODEL streamflow values
#' (DEFAULT="q_cms").
#' @param strflowDf.mod2 The SECOND MODEL streamflow time series dataframe (e.g., output from \code{\link{ReadFrxstPts}})
#' already processed through \code{\link{CalcFdc}}. The dataframe must contain a column of streamflow values and a
#' corresponding column (named "<strflowCol>.fdc") of flow exceedance probabilities.
#' @param strflowCol.mod2 The name of the column containing the SECOND MODEL streamflow values
#' (DEFAULT="q_cms").
#' @param spline (TRUE or FALSE) Option to add spline-fit curves to the plot (DEFAULT=TRUE).
#' @param logy (TRUE or FALSE) Optional flag to set the y-axis to log-scale (DEFAULT=TRUE).
#' @param labelObs Optional label for the observed streamflow (DEFAULT="Observed")
#' @param labelMod1 Optional label for the FIRST MODEL (DEFAULT="Model 1")
#' @param labelMod2 Optional label for the SECOND MODEL (DEFAULT="Model 2")
#' @return A plot of flow (y) vs. flow exceedance probabilities (x).
#'
#' @examples
#' ## Take a time series of observed 5-minute streamflow values for Fourmile Creek (obsStr5min.fc) and two model
#' ## runs (mod1Str5min.fc, mod2Str5min.fc), all with streamflow columns named "q_cms" and already processed
#' ## through "CalcFdc", and plot the flow duration curves for all three.
#'
#' PlotFdcCompare(obsStr5min.fc, "q_cms", mod1Str5min.fc, "q_cms", strflowDf.mod2=mod2Str5min.fc, strflowCol.mod2="q_cms", labelObs="Observed Fourmile Creek (5-min)", labelMod1="1-D Flow Model", labelMod2="2-D Flow Model")
#' @export
PlotFdcCompare <- function(strflowDf.obs, strflowCol.obs="q_cms",
                            strflowDf.mod1, strflowCol.mod1="q_cms",
                            strflowDf.mod2=NULL, strflowCol.mod2="q_cms",
                            spline=TRUE, logy=TRUE,
                            labelObs="Observed", labelMod1="Model 1", labelMod2="Model 2") {
# PREP DATA
if (spline) {
    fdcSplineFun.obs <- splinefun(strflowDf.obs[,paste0(strflowCol.obs,".fdc")], strflowDf.obs[,strflowCol.obs], method='natural')
    fdcSplineFun.mod1 <- splinefun(strflowDf.mod1[,paste0(strflowCol.mod1,".fdc")], strflowDf.mod1[,strflowCol.mod1], method='natural')
    if (!is.null(strflowDf.mod2)) {
        fdcSplineFun.mod2 <- splinefun(strflowDf.mod2[,paste0(strflowCol.mod2,".fdc")], strflowDf.mod2[,strflowCol.mod2], method='natural')
        }
    }
if (!is.null(strflowDf.mod2)) {
	combmin <- max(0.001, min(min(strflowDf.obs[,strflowCol.obs],na.rm=T), min(strflowDf.mod1[,strflowCol.mod1],na.rm=T), min(strflowDf.mod2[,strflowCol.mod2],na.rm=T)))
	print(paste("Combined min flow for y-axis (capped at 0.001):",combmin))
	combmax <- max(max(strflowDf.obs[,strflowCol.obs],na.rm=T), max(strflowDf.mod1[,strflowCol.mod1],na.rm=T), max(strflowDf.mod2[,strflowCol.mod2], na.rm=T))
	print(paste("Combined max flow for y-axis:",combmax))
	}
else {
	combmin <- max(0.001,min(min(strflowDf.obs[,strflowCol.obs],na.rm=T), min(strflowDf.mod1[,strflowCol.mod1],na.rm=T)))
	print(paste("Combined min flow for y-axis (capped at 0.001):",combmin))
	combmax <- max(max(strflowDf.obs[,strflowCol.obs],na.rm=T), max(strflowDf.mod1[,strflowCol.mod1],na.rm=T))
	print(paste("Combined max flow for y-axis:",combmax))
	}
# PLOT
dev.new(width=10, height=6)
if (logy) {
	plot(strflowDf.obs[,paste0(strflowCol.obs,".fdc")], strflowDf.obs[,strflowCol.obs], log='y', xlab="Probability of Exceedance", ylab=c(paste("Flow", deparse(substitute(strflowCol.obs)), "(log scale)")), main=c(paste("Flow Duration Curve:", labelObs)), ylim=c(combmin,combmax))
	}
else {
	plot(strflowDf.obs[,paste0(strflowCol.obs,".fdc")], strflowDf.obs[,strflowCol.obs], xlab="Probability of Exceedance", ylab=c(paste("Flow", deparse(substitute(strflowCol.obs)))), main=c(paste("Flow Duration Curve:", labelObs)), ylim=c(combmin,combmax))
	}
if (spline) {
    curve(fdcSplineFun.obs(x), col='red', lwd=2, lty=1, add=TRUE)
    }
points(strflowDf.mod1[,paste0(strflowCol.mod1,".fdc")], strflowDf.mod1[,strflowCol.mod1],col='blue')
if (spline) {
    curve(fdcSplineFun.mod1(x), col='cyan', lwd=2, lty=1, add=TRUE)
    }
if (!is.null(strflowDf.mod2)) {
	points(strflowDf.mod2[,paste0(strflowCol.mod2,".fdc")], strflowDf.mod2[,strflowCol.mod2],col='darkgreen')
    if (spline) {
        curve(fdcSplineFun.mod2(x), col='green', lwd=2, lty=1, add=TRUE)
        legend('topright', legend=c(labelObs, paste(labelObs,"- Curve Fit"), labelMod1, paste(labelMod1,"- Curve Fit"), labelMod2, paste(labelMod2,"- Curve Fit")), lty=c(NA,1,NA,1,NA,1), pch=c(1,NA,1,NA,1,NA), lwd=c(NA,1,NA,1,NA,1), col=c("black","red","blue","cyan","darkgreen","green"), bty='n')
    }
    else {
        legend('topright', legend=c(labelObs, labelMod1, labelMod2), pch=c(1,1,1), col=c("black","blue","darkgreen"), bty='n')
            }
    mtext(c(paste("Obs: ", labelObs, ", ", min(format(strflowDf.obs$POSIXct,"%Y")), "-", max(format(strflowDf.obs$POSIXct,"%Y")), ", n=", sum(!is.na(strflowDf.obs[,strflowCol.obs])), " (", round(sum(is.na(strflowDf.obs[,strflowCol.obs]))/length(strflowDf.obs[,strflowCol.obs])*100,2), "% missing)", "\nModel 1: ", labelMod1, ", ",  min(format(strflowDf.mod1$POSIXct,"%Y")), "-", max(format(strflowDf.mod1$POSIXct,"%Y")), ", n=", sum(!is.na(strflowDf.mod1[,strflowCol.mod1])), "   Model 2: ", labelMod2, ", ",  min(format(strflowDf.mod2$POSIXct,"%Y")), "-", max(format(strflowDf.mod2$POSIXct,"%Y")), ", n=", sum(!is.na(strflowDf.mod2[,strflowCol.mod2])), sep="")), side=3, line=0.0, cex=0.8)
	}
else {
    if (spline) {
        legend('topright', legend=c(labelObs,paste(labelObs,"- Curve Fit"),labelMod1, paste(labelMod1,"- Curve Fit")), lty=c(NA,1,NA,1), pch=c(1,NA,1,NA), lwd=c(NA,1,NA,1), col=c("black","red","blue","cyan"), bty='n')
        }
    else {
    	legend('topright', legend=c(labelObs,labelMod1), pch=c(1,1), col=c("black","blue"), bty='n')
        }
    mtext(c(paste("Obs: ", labelObs, ", ", min(format(strflowDf.obs$POSIXct,"%Y")), "-", max(format(strflowDf.obs$POSIXct,"%Y")), ", n=", sum(!is.na(strflowDf.obs[,strflowCol.obs])), " (", round(sum(is.na(strflowDf.obs[,strflowCol.obs]))/length(strflowDf.obs[,strflowCol.obs])*100,2), "% missing)", "   Model 1: ", labelMod1, ", ",  min(format(strflowDf.mod1$POSIXct,"%Y")), "-", max(format(strflowDf.mod1$POSIXct,"%Y")), ", n=", sum(!is.na(strflowDf.mod1[,strflowCol.mod1])),sep="")),side=3,line=0.2,cex=1.0)
	}
}





